language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

before_install:
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "install.packages('covr')"
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

before_deploy:
  - Rscript -e "devtools::document()"

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
